# Colores
BLANCO = (255, 255, 255)
NEGRO = (0, 0, 0)
GRIS = (206, 206, 206)
AZUL = (30, 136, 229)

#Seteos Juego
ANCHO_PANTALLA = 400
ALTO_PANTALLA = 450
ALTO_TEXTO = 50
CANTIDAD_TARJETAS_H = 4
CANTIDAD_TARJETAS_V = 4
CANTIDAD_TARJETAS_UNICAS = int((CANTIDAD_TARJETAS_H*CANTIDAD_TARJETAS_V)/2)
ANCHO_TARJETA = int(ANCHO_PANTALLA / CANTIDAD_TARJETAS_H)
ALTO_TARJETA =int( (ALTO_PANTALLA - ALTO_TEXTO)/ CANTIDAD_TARJETAS_V)
PATH_RECURSOS = r"C:\\Users\\Profesor\\Desktop\\PL1_PY_2022_2C\\clase_16\\recursos\\"
