lista_personajes =\
[
  {
    "nombre": "Howard the Duck",
    "identidad": "Howard (Last name unrevealed)",
    "empresa": "Marvel Comics",
    "altura": "79.349999999999994",
    "peso": "18.449999999999999",
    "genero": "M",
    "color_ojos": "Brown",
    "color_pelo": "Yellow",
    "fuerza": "2",
    "inteligencia": ""
  },
  {
    "nombre": "Rocket Raccoon",
    "identidad": "Rocket Raccoon",
    "empresa": "Marvel Comics",
    "altura": "122.77",
    "peso": "25.73",
    "genero": "M",
    "color_ojos": "Brown",
    "color_pelo": "Brown",
    "fuerza": "5",
    "inteligencia": "average"
  },
  {
    "nombre": "Wolverine",
    "identidad": "Logan",
    "empresa": "Marvel Comics",
    "altura": "160.69999999999999",
    "peso": "135.21000000000001",
    "genero": "M",
    "color_ojos": "Blue",
    "color_pelo": "Black",
    "fuerza": "35",
    "inteligencia": "good"
  },
  {
    "nombre": "Black Widow",
    "identidad": "Natasha Romanoff",
    "empresa": "Marvel Comics",
    "altura": "170.78999999999999",
    "peso": "59.340000000000003",
    "genero": "F",
    "color_ojos": "Green",
    "color_pelo": "Auburn",
    "fuerza": "15",
    "inteligencia": "good"
  },
  {
    "nombre": "Mystique",
    "identidad": "Raven Darkholme",
    "empresa": "Marvel Comics",
    "altura": "178.65000000000001",
    "peso": "54.960000000000001",
    "genero": "F",
    "color_ojos": "Yellow (without irises)",
    "color_pelo": "Red / Orange",
    "fuerza": "15",
    "inteligencia": "good"
  },
  {
    "nombre": "Spider-Man",
    "identidad": "Peter Parker",
    "empresa": "Marvel Comics",
    "altura": "178.28",
    "peso": "74.25",
    "genero": "M",
    "color_ojos": "Hazel",
    "color_pelo": "Brown",
    "fuerza": "55",
    "inteligencia": "high"
  },
  {
    "nombre": "Storm",
    "identidad": "Ororo Munroe",
    "empresa": "Marvel Comics",
    "altura": "180.72",
    "peso": "57.5",
    "genero": "F",
    "color_ojos": "Blue",
    "color_pelo": "White",
    "fuerza": "10",
    "inteligencia": "good"
  },
  {
    "nombre": "Gamora",
    "identidad": "Gamora Zen Whoberi Ben Titan",
    "empresa": "Marvel Comics",
    "altura": "183.65000000000001",
    "peso": "77.769999999999996",
    "genero": "F",
    "color_ojos": "Yellow",
    "color_pelo": "Black",
    "fuerza": "85",
    "inteligencia": "good"
  },
  {
    "nombre": "Thing",
    "identidad": "Ben Grimm",
    "empresa": "Marvel Comics",
    "altura": "183.55000000000001",
    "peso": "225.41999999999999",
    "genero": "M",
    "color_ojos": "Blue",
    "color_pelo": "No Hair",
    "fuerza": "85",
    "inteligencia": "good"
  },
  {
    "nombre": "Thor",
    "identidad": "Thor Odinson",
    "empresa": "Marvel Comics",
    "altura": "198.34999999999999",
    "peso": "288.61000000000001",
    "genero": "M",
    "color_ojos": "Blue",
    "color_pelo": "Blond",
    "fuerza": "100",
    "inteligencia": "good"
  },
  {
    "nombre": "Colossus",
    "identidad": "Piotr Nikolaievitch Rasputin",
    "empresa": "Marvel Comics",
    "altura": "226.13",
    "peso": "225.52000000000001",
    "genero": "M",
    "color_ojos": "Silver",
    "color_pelo": "Black",
    "fuerza": "85",
    "inteligencia": "good"
  },
  {
    "nombre": "Hulk",
    "identidad": "Bruce Banner",
    "empresa": "Marvel Comics",
    "altura": "244.40000000000001",
    "peso": "630.89999999999998",
    "genero": "M",
    "color_ojos": "Green",
    "color_pelo": "Green",
    "fuerza": "100",
    "inteligencia": "high"
  },
  {
    "nombre": "Groot",
    "identidad": "Groot",
    "empresa": "Marvel Comics",
    "altura": "701.12",
    "peso": "4.8200000000000003",
    "genero": "M",
    "color_ojos": "Yellow",
    "color_pelo": "",
    "fuerza": "85",
    "inteligencia": "good"
  },
  {
    "nombre": "Daredevil",
    "identidad": "Matt Murdock",
    "empresa": "Marvel Comics",
    "altura": "183.68000000000001",
    "peso": "90.450000000000003",
    "genero": "M",
    "color_ojos": "Blue",
    "color_pelo": "Red",
    "fuerza": "15",
    "inteligencia": "good"
  },
  {
    "nombre": "Nick Fury",
    "identidad": "Nicholas Joseph Fury",
    "empresa": "Marvel Comics",
    "altura": "185.88",
    "peso": "99.280000000000001",
    "genero": "M",
    "color_ojos": "Brown",
    "color_pelo": "Brown / White",
    "fuerza": "15",
    "inteligencia": "good"
  },
  {
    "nombre": "Punisher",
    "identidad": "Frank Castle",
    "empresa": "Marvel Comics",
    "altura": "183.25999999999999",
    "peso": "90.900000000000006",
    "genero": "M",
    "color_ojos": "Blue",
    "color_pelo": "Black",
    "fuerza": "20",
    "inteligencia": "good"
  },
  {
    "nombre": "Star-Lord",
    "identidad": "Peter Jason Quill",
    "empresa": "Marvel Comics",
    "altura": "188.25",
    "peso": "79.209999999999994",
    "genero": "M",
    "color_ojos": "Blue",
    "color_pelo": "Blond",
    "fuerza": "20",
    "inteligencia": "good"
  },
  {
    "nombre": "Deadpool",
    "identidad": "Wade Wilson",
    "empresa": "Marvel Comics",
    "altura": "188.0",
    "peso": "95.319999999999993",
    "genero": "M",
    "color_ojos": "Brown",
    "color_pelo": "No Hair",
    "fuerza": "35",
    "inteligencia": "good"
  },
  {
    "nombre": "Captain America",
    "identidad": "Steve Rogers",
    "empresa": "Marvel Comics",
    "altura": "188.00999999999999",
    "peso": "108.94",
    "genero": "M",
    "color_ojos": "blue",
    "color_pelo": "blond",
    "fuerza": "20",
    "inteligencia": "good"
  },
  {
    "nombre": "Ghost Rider",
    "identidad": "Johnny Blaze",
    "empresa": "Marvel Comics",
    "altura": "188.50999999999999",
    "peso": "99.200000000000003",
    "genero": "M",
    "color_ojos": "Red",
    "color_pelo": "No Hair",
    "fuerza": "55",
    "inteligencia": "average"
  },
  {
    "nombre": "Blade",
    "identidad": "Eric Brooks",
    "empresa": "Marvel Comics",
    "altura": "188.44999999999999",
    "peso": "97.400000000000006",
    "genero": "M",
    "color_ojos": "Brown",
    "color_pelo": "Black",
    "fuerza": "30",
    "inteligencia": "good"
  },
  {
    "nombre": "Hawkeye",
    "identidad": "Clint Barton",
    "empresa": "Marvel Comics",
    "altura": "191.00999999999999",
    "peso": "104.93000000000001",
    "genero": "M",
    "color_ojos": "Blue",
    "color_pelo": "Blond",
    "fuerza": "15",
    "inteligencia": "average"
  },
  {
    "nombre": "Drax the Destroyer",
    "identidad": "Arthur Sampson Douglas",
    "empresa": "Marvel Comics",
    "altura": "193.00999999999999",
    "peso": "306.42000000000002",
    "genero": "M",
    "color_ojos": "Red",
    "color_pelo": "No Hair",
    "fuerza": "80",
    "inteligencia": "average"
  },
  {
    "nombre": "Iron Man",
    "identidad": "Tony Stark",
    "empresa": "Marvel Comics",
    "altura": "198.91",
    "peso": "191.88",
    "genero": "M",
    "color_ojos": "Blue",
    "color_pelo": "Black",
    "fuerza": "85",
    "inteligencia": "high"
  }
]